## Modified by Sam KUON - 28/07/17
FROM centos:latest
MAINTAINER Sam KUON "sam.kuonssp@gmail.com"

# System timezone
ENV TZ=Asia/Phnom_Penh
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Repositories and packages
RUN yum -y install epel-release && \
    rpm -Uvh https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm

RUN yum -y update && \
    yum -y install \
	php70u \
	php70u-mysqlnd \
	php70u-common \
	php70u-mbstring \
	mod_php70u \
	php70u-ldap \
	httpd \
	wget &&\
    yum clean all

# Download Mediawiki
RUN cd /tmp/ && wget http://iptrack.sourceforge.net/ipplan.tar.gz && \
	tar xzvf ipplan.tar.gz -C /usr/src/ && \
	rm -rf /tmp/ipplan.tar.gz*

# Copy run-httpd script to image
ADD ./conf.d/run-httpd.sh /run-httpd.sh
RUN chmod -v +x /run-httpd.sh

EXPOSE 80 443

CMD ["/run-httpd.sh"]

