version: '3'
services:
  ipplan:
    image: cent7-ipplan:latest
    container_name: ipplan-beta
    network_mode: bridge
    ports:
      - 8082:80
    environment:
      - DB_IPPLAN_HOST=172.22.2.10
      - DB_IPPLAN_USER=user_ipplan
      - DB_IPPLAN_NAME=db_ipplan
      - DB_IPPLAN_PASSWORD=P@ssw0rd#1
    volumes:
      - ./ipplan:/var/www/html/
